In [93]:
import numpy as np
from grapy import np_extensions as ne
from grapy import grapy as gp

In [2]:
#a = np.array([[1,2],[2,3],[3,4]])
#b = np.array([[1,2],[2,4]])
a = np.array([[1,2],[2,3]])
b = np.array([[1,2]])

np.expand_dims(b, 1) == a
#np_extensions.contains_vec(a,b, axis=0)

array([[[ True,  True],
        [False, False]]])

In [3]:
np.array([1, 2]).shape == (2, 2)

False

In [4]:
#g = Graph.from_edges(np.array([[1,2], [2,3], [3,1], [3,4], [4,5], [5,6], [6,4], [6,1]]))
g = gp.from_edges([[1,2], [2,3], [3,1], [3,4], [4,5], [5,6], [6,4], [6,1]])
print(g)

([1 2 3 4 5 6]
[[1 2]
 [2 3]
 [3 1]
 [3 4]
 [4 5]
 [5 6]
 [6 4]
 [6 1]])


In [5]:
(
    g.verts,
    g.edges,
    len(g),
    g.get_edges([1, 2, 3], [4, 5, 6]),
    g.neighb([1, 3]),
    1 in g,
    7 in g,
    [1,2] in g,
    [1,5,7] in g,
    [[1,2],[2,3]] in g,
    [[1,2],[2,5]] in g,
    gp.from_edges([[1,2],[2,3]]) in g,
    gp.from_edges([[1,2],[2,5]]) in g,
    g[[1,2,3,5]],
)

(array([1, 2, 3, 4, 5, 6]),
 array([[1, 2],
        [2, 3],
        [3, 1],
        [3, 4],
        [4, 5],
        [5, 6],
        [6, 4],
        [6, 1]]),
 6,
 array([[3, 4],
        [6, 1]]),
 array([1, 2, 3, 4, 6]),
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 ggraph(
 edges=array([1, 2, 3, 5]),
 verts=array([[1, 2],
        [2, 3],
        [3, 1]])))

In [83]:
def contains_edges(edges, e):
    #return (((edges[:]==e) | (edges[:]==e[::-1])).all(axis=1)).any()

    e_fliped = np.flip(e, axis=1)
    edges_expanded = np.expand_dims(edges, 1)

    comparsion1 = edges_expanded == e
    comparsion1 = comparsion1.all(axis=2)
    comparsion2 = edges_expanded == e_fliped
    comparsion2 = comparsion2.all(axis=2)
    comparsion = comparsion1 | comparsion2
    return comparsion.any(axis=0)

In [84]:
a = np.array([[1,2], [2,3], [3,1], [3,4], [4,5], [5,6], [6,4], [6,1]])
#a = np.array([[1,2], [2,3]])
e = np.array([[2,5], [2,3], [1,6]])
#e = np.array([[2,5]])

contains_edges(a, e)#, contains_edge(a, [[2,3]])

array([False,  True,  True])

In [90]:
np.expand_dims([[1,2], [3,4]])

TypeError: _expand_dims_dispatcher() missing 1 required positional argument: 'axis'

In [92]:
np.array([1,2])[np.newaxis]

array([[1, 2]])

In [ ]:


if type(verts) is int:
    verts = np.array([verts])

mask1 = ne.contains_vec(verts, g.edges[:,0])
mask2 = ne.contains_vec(verts, g.edges[:,1])
neighb1 = g.edges[mask1][:,1]
neighb2 = g.edges[mask2][:,0]

#return np.append(neighb1, neighb2)
return np.unique([neighb1, neighb2])