In [93]:
import numpy as np
from grapy import np_extensions as ne
from grapy import grapy as gp

In [2]:
#a = np.array([[1,2],[2,3],[3,4]])
#b = np.array([[1,2],[2,4]])
a = np.array([[1,2],[2,3]])
b = np.array([[1,2]])

np.expand_dims(b, 1) == a
#np_extensions.contains_vec(a,b, axis=0)

array([[[ True,  True],
        [False, False]]])

In [3]:
np.array([1, 2]).shape == (2, 2)

False

In [4]:
#g = Graph.from_edges(np.array([[1,2], [2,3], [3,1], [3,4], [4,5], [5,6], [6,4], [6,1]]))
g = gp.from_edges([[1,2], [2,3], [3,1], [3,4], [4,5], [5,6], [6,4], [6,1]])
print(g)

([1 2 3 4 5 6]
[[1 2]
 [2 3]
 [3 1]
 [3 4]
 [4 5]
 [5 6]
 [6 4]
 [6 1]])


In [5]:
(
    g.verts,
    g.edges,
    len(g),
    g.get_edges([1, 2, 3], [4, 5, 6]),
    g.neighb([1, 3]),
    1 in g,
    7 in g,
    [1,2] in g,
    [1,5,7] in g,
    [[1,2],[2,3]] in g,
    [[1,2],[2,5]] in g,
    gp.from_edges([[1,2],[2,3]]) in g,
    gp.from_edges([[1,2],[2,5]]) in g,
    g[[1,2,3,5]],
)

(array([1, 2, 3, 4, 5, 6]),
 array([[1, 2],
        [2, 3],
        [3, 1],
        [3, 4],
        [4, 5],
        [5, 6],
        [6, 4],
        [6, 1]]),
 6,
 array([[3, 4],
        [6, 1]]),
 array([1, 2, 3, 4, 6]),
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 ggraph(
 edges=array([1, 2, 3, 5]),
 verts=array([[1, 2],
        [2, 3],
        [3, 1]])))

In [113]:
a = np.array([1,2,3])
b = np.array([1,2,4])

a[(np.expand_dims(b, 1) != a).all(axis=0)], np.setdiff1d(a,b), np.union1d(a,b)

(array([3]), array([3]), array([1, 2, 3, 4]))

In [114]:
a = np.array([[1,2], [3,4]])
b = np.array([1,2])

np.setdiff1d(a,b)

array([3, 4])

# ideas
- sort edges for easy compability
- methods to add:
  - remove single verts